### ISSUE TITLE
Feature: User can create account to log in

### ISSUE THREAD

**Issue by tangm28** [tangm28/Workout-Journal_LFZ-Final-Project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can create account to log in

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to create a unique username and password to log into their personal workout journal
Upon account creation, user can build their profile

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/93749849/154370580-c3af567e-6d51-418f-acb9-0d84d9227d37.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.
- [x] Create wireframe for Log In page
- [x] User can log in and view main page if they input the correct credentials 
- [x] User without an account can either register an account or start as a guest
        - [ ] Create Register wireframe to create new account
        - [ ] Unique username must be given
        - [ ] Password and Confirm Password needs to match
- [x] Create wireframe for Create Profile
        - [ ] New account or new guest user is brought to Create Profile page

### 🐘 Database

- [x] Update `schema.sql` to store new account creation
- [x] Update `schema.sql` to store new account profile details

### ☁️ Server

- [x] Update `server/index.js` to handle log in requests
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### 🧑‍⚕️ Clean Up

- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
