### ISSUE TITLE
Feature: User can finish account creation by inputting their 1 rep maxes

### ISSUE THREAD

**Issue by tangm28** [tangm28/Workout-Journal_LFZ-Final-Project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can finish account creation by inputting their 1 rep maxes

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can input their 1 rep maxes for Bench, Squat, Deadlift, and Overhead Press.
User can select if they want to use imperial or metric units of measurement
User can use a calculator by selecting the link if they are unsure. The link opens up a calculator modal

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/93749849/154371698-61865ff4-a9db-470c-9ae6-7dd23a198ec3.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.
- [ ] Create Let's Get Started wireframe
- [ ] Create a form for user data
       - [ ] Create a toggle button for measurement unit
- [ ] Create a calculator modal

### 🐘 Database

- [ ] Update `schema.sql` to store the 1 rep maxes data

### 🧑‍⚕️ Clean Up

- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
